# Generated by Django 2.2.5 on 2021-11-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('brand', models.CharField(max_length=256, verbose_name='manufacture')),
                ('size', models.CharField(max_length=256, verbose_name='size')),
                ('price', models.FloatField(verbose_name='price')),
                ('available', models.IntegerField(verbose_name='avai')),
                ('link', models.CharField(max_length=256, verbose_name='purchasing link')),
                ('fe', models.FloatField(verbose_name='filtration efficiency')),
            ],
            options={
                'verbose_name': 'Mask for Kids',
            },
        ),
    ]
